const POSTURE_STATUS = {
  GOOD_POSTURE: 'GOOD_POSTURE',
  NORMAL: 'NORMAL',
  SLUMPED_WARNING: 'SLUMPED_WARNING',
  SLUMPED_CAUTION: 'SLUMPED_CAUTION',
  TURTLE_NECK_WARNING: 'TURTLE_NECK_WARNING',
  TURTLE_NECK_CAUTION: 'TURTLE_NECK_CAUTION',
  TILTED_WARNING: 'TILTED_WARNING',
  TILTED_CAUTION: 'TILTED_CAUTION',
  LEANING_ON_HAND: 'LEANING_ON_HAND',
  STATIC_WARNING: 'STATIC_WARNING',
  STATIC_CAUTION: 'STATIC_CAUTION',
  UNKNOWN: 'UNKNOWN',
};

const POSE_TYPE = {
  GOOD: 'GOOD',
  BAD: 'BAD',
};

const GOOD_POSTURE_STATUS = [
  POSTURE_STATUS.GOOD_POSTURE,
  POSTURE_STATUS.NORMAL,
];

module.exports = {
  POSTURE_STATUS,
  POSE_TYPE,
  GOOD_POSTURE_STATUS,
};