const RESPONSE_CODES = {
  SUCCESS: 'SUCCESS',
  REQUEST_FAILED: 'REQUEST_FAILED',

  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_NICK: 'INVALID_NICK',
  INVALID_IMMERSION_ID: 'INVALID_IMMERSION_ID',
  INVALID_OAUTH_STATE: 'INVALID_OAUTH_STATE',

  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_NICK: 'DUPLICATE_NICK',

  LOGIN_FAILED: 'LOGIN_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  AUTH_CODE_EXPIRED: 'AUTH_CODE_EXPIRED',
  INVALID_AUTH_CODE: 'INVALID_AUTH_CODE',

  OAUTH_PROVIDER_UNSUPPORTED: 'OAUTH_PROVIDER_UNSUPPORTED',
  OAUTH_CALLBACK_FAILED: 'OAUTH_CALLBACK_FAILED',
  OAUTH_PROFILE_NOT_FOUND: 'OAUTH_PROFILE_NOT_FOUND',
  OAUTH_EMAIL_REQUIRED: 'OAUTH_EMAIL_REQUIRED',
};

module.exports = {
  RESPONSE_CODES,
};